logging:
  level:
    web: debug
grpc:
  server:
    port: 9090
    reflection-service-enabled: true
spring:
  main:
    web-application-type: none
  cassandra:
    local-datacenter: dc1
    port: 31646
    keyspace-name: wallet
    username: cluster1-superuser
    password: t72v7ioLWEfo7fPbiWfjO1YZ2NWoxxAjLuQaqNdNA8wSbFKicPirjA
    contact-points: 10.8.0.7
    schema-action: create_if_not_exists