apiVersion: v1
kind: Pod
metadata:
    labels:
        app: jenkins-ci
spec:
    containers:
        - name: gradle
          image: gradle:8.10.2-jdk23-jammy
          command:
              - cat
          tty: true
          env:
              - name: GRADLE_RO_DEP_CACHE
                value: /home/gradle/.gradle-read-only/caches
          volumeMounts:
              - mountPath: /home/gradle/.gradle-read-only/caches/modules-2
                name: gradle-cache
                readOnly: true
#        - name: python
#          image: python:3.9-alpine
#          command:
#              - cat
#          tty: true
#        - name: kaniko
#          image: gcr.io/kaniko-project/executor:debug
#          tty: true
#          command:
#              - /busybox/cat
#          volumeMounts:
#              - name: kaniko-secret
#                mountPath: /kaniko/.docker
        - name: jnlp
          image: jenkins/jnlp-agent-docker:latest
          resources:
              limits:
                  memory: 2Gi
              requests:
                  memory: 2Gi
          imagePullPolicy: Always
          env:
              - name: POD_IP
                valueFrom:
                    fieldRef:
                        fieldPath: status.podIP
              - name: DOCKER_HOST
                value: tcp://localhost:2375
        - name: docker-in-docker
          image: docker:dind
          securityContext:
              privileged: true
          volumeMounts:
              - name: doc-in-doc-storage
                mountPath: /var/lib/docker
        - name: docker
          image: docker:latest
          command:
              - cat
          tty: true
          volumeMounts:
              - mountPath: /var/run/docker.sock
                name: docker-sock
    volumes:
        - name: gradle-cache
          hostPath:
              path: /home/tik/.gradle/caches/modules-2
        - name: kaniko-secret
          secret:
              secretName: dockercred
              items:
                  - key: .dockerconfigjson
                    path: config.json
        - name: doc-in-doc-storage
          emptyDir: { }
        - name: docker-sock
          hostPath:
              path: /var/run/docker.sock