apiVersion: v1
kind: ConfigMap
metadata:
  name: nio-client
data:
  application.yaml: |-
    spring:
      main:
        web-application-type: reactive
      threads:
        virtual:
          enabled: true
    grpc:
      client:
        bank-account-service:
          address: static://10.233.90.5:9090
          negotiation-type: plaintext
    logging:
      level:
        web: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nio-client
  labels:
    app: nio-client
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nio-client
  template:
    metadata:
      labels:
        app: nio-client
    spec:
      containers:
        - name: nio-client
          image: tiktuzki/nio-client:latest
          imagePullPolicy: Always
          #          resources:
          #            limits:
          #              memory: '1Gi'
          #              cpu: '2'
          args: [ ]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod'
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 120
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 150
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: nio-client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nio-client
  name: nio-client
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30005
  selector:
    app: nio-client
  type: NodePort