spring:
  main:
    web-application-type: reactive
  threads:
    virtual:
      enabled: true
grpc:
  client:
    bank-account-service:
      address: static://127.0.0.1:9090
      negotiation-type: plaintext
server:
  port: 8080
management:
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    web: info
    io.grpc: info
    org.nio: debug
    org.nio.client.transaction: debug # log transaction
    reactor.netty: debug
