spring:
  main:
    web-application-type: reactive
  threads:
    virtual:
      enabled: true
logging:
  level:
    web: debug
grpc:
  client:
    bank-account-service:
      address: static://localhost:9090
      negotiation-type: plaintext
server:
  port: 8080