grpc:
  server:
    port: 9090
    reflection-service-enabled: true
    keep-alive-timeout: 20s
spring:
  main:
    web-application-type: reactive
  cassandra:
    #    local-datacenter: dc1
    #    port: 31646
    keyspace-name: nio_lab
    #    username: cluster1-superuser
    #    password: Nt72v7ioLWEfo7fPbiWfjO1YZ2NWoxxAjLuQaqNdNA8wSbFKicPirjA
    #    contact-points: 10.8.0.7
    schema-action: create_if_not_exists
    config: classpath:cassandra-application.conf
    request:
      consistency: local_quorum
      serial-consistency: local_serial
  threads:
    virtual:
      enabled: true
logging:
  level:
    org.nio: error
    org.nio.transaction.TranLogger: error
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: ${LOG_CASSANDRA:error}
    io.grpc: error
    reactor.netty: off
    com.amazon: ${LOG_AWS:info}
    software.amazon: ${LOG_AWS:info}
    com.datastax: ${LOG_CASSANDRA:error}
    web: info
    root: info
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
server:
  port: 8080
sqs:
  region: ap-southeast-1
  name: nio-lab
  url: https://sqs.ap-southeast-1.amazonaws.com/730335282524/nio-lab
transaction:
  receive-message-wait-time: 20s
  buffer-size: 10
  buffer-time: 50s
  number-of-messages: 10
