grpc:
  server:
    port: 9090
    reflection-service-enabled: true
spring:
  main:
    web-application-type: reactive
  cassandra:
    #    local-datacenter: dc1
    #    port: 31646
    keyspace-name: nio_lab
    #    username: cluster1-superuser
    #    password: Nt72v7ioLWEfo7fPbiWfjO1YZ2NWoxxAjLuQaqNdNA8wSbFKicPirjA
    #    contact-points: 10.8.0.7
    schema-action: create_if_not_exists
    config: classpath:cassandra-application.conf
  threads:
    virtual:
      enabled: true
logging:
  level:
    org.nio: info
    org.nio.transaction.TranLogger: error
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: off
    io.grpc: off
    reactor.netty: off
    com.amazon: off
    com.datastax: off
    web: info
    root: info
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
server:
  port: 8081