grpc:
  server:
    port: 9090
    reflection-service-enabled: true
spring:
  main:
    web-application-type: none
  cassandra:
    #    local-datacenter: dc1
    #    port: 31646
    keyspace-name: nio_lab
    #    username: cluster1-superuser
    #    password: Nt72v7ioLWEfo7fPbiWfjO1YZ2NWoxxAjLuQaqNdNA8wSbFKicPirjA
    #    contact-points: 10.8.0.7
    schema-action: create_if_not_exists
    config: cassandra-application.conf
  threads:
    virtual:
      enabled: true
logging:
  level:
    web: debug
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: info
