grpc:
  server:
    port: 9090
    reflection-service-enabled: true
spring:
  main:
    web-application-type: reactive
  cassandra:
    #    local-datacenter: dc1
    #    port: 31646
    keyspace-name: nio_lab
    #    username: cluster1-superuser
    #    password: Nt72v7ioLWEfo7fPbiWfjO1YZ2NWoxxAjLuQaqNdNA8wSbFKicPirjA
    #    contact-points: 10.8.0.7
    schema-action: create_if_not_exists
    config: classpath:cassandra-application.conf
  threads:
    virtual:
      enabled: true
logging:
  level:
    org.nio: debug
    org.nio.transaction.TranLogger: debug
    web: info
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: debug
    io.grpc: info
    reactor.netty: info
    root: info
    com.amazon: debug
    com.amazonaws: debug
    javax.jms: debug
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
server:
  port: 8081