scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '172.17.0.1:9090' ]
  - job_name: 'nio-lab'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ '172.17.0.1:8081' ]
#  - job_name: 'nio-lab-grpc'
#    metrics_path: '/actuator/metrics'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['localhost:8081']
